services:
  nginx:
    build: ./nginx
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    depends_on:
      - backend
      - frontend

  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=${NODE_ENV:-development}

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - backend